name: Bug Report
description: Create a report to help us fix an error you are encountering
title: "[Bug report title]"
labels: ["bug report / hotfix PR"]

body:
  - type: dropdown
    attributes:
      label: Installation Type
      description: Are you running pVACtools standalone or using a Docker container?
      multiple: false
      options:
        - Standalone 
        - Docker
    validations:
      required: true
  - type: input
    attributes:
      label: pVACtools Version / Docker Image
      description: If you're running pVACtools standalone, which version do you have installed (`pvactools -v`)? If you are using Docker, which Docker container are you running (e.g. `griffithlab/pvactools:3.1.3-slim`)?
    validations:
      required: true
  - type: input
    attributes:
      label: Python Version
      description: If you're running pVACtools standalone, which Python version are you using (`python -V`)?
  - type: input
    attributes:
      label: Operating System
      description: If you're running pVACtools standalone, what operating system are you running on?
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: How to reproduce this bug
      description: What is the pVACtools command you ran?
      render: Shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: Input files
      description: Attach any input files that can be used to reproduce this problem. Please limit file size and include only the minimal number of variants needed to replicate the issue.
  - type: textarea
    attributes:
      label: Log output
      description: The log that gets written to standard out
    validations:
      required: true
  - type: textarea
    attributes:
      label: Output files
      description: If your bug is related to the contents of an output file, please attach the output file(s) here.
